apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotics-sim
spec:
  replicas: 3  # Run 3 parallel simulations
  selector:
    matchLabels:
      app: robotics-sim
  template:
    metadata:
      labels:
        app: robotics-sim
    spec:
      containers:
      - name: robotics-sim
        image: robotics-sim:latest
        env:
        - name: AWS_REGION
          value: "us-west-2"
        - name: KINESIS_STREAM_NAME
          value: "robotics-sim-stream"
        - name: SIMULATION_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretRef:
              name: aws-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretRef:
              name: aws-credentials
              key: aws-secret-access-key
