apiVersion: batch/v1
kind: Job
metadata:
  name: robotics-sim-job
  namespace: robotics-sim
spec:
  completions: 3
  parallelism: 3  # Keep 3 parallel runs
  backoffLimit: 2  # Reduced to fail faster
  template:
    metadata:
      labels:
        app: robotics-sim
    spec:
      restartPolicy: Never  # Changed to Never to preserve failed pod logs
      serviceAccountName: robotics-sim-sa
      containers:
        - name: robotics-sim
          image: 805791260265.dkr.ecr.us-west-2.amazonaws.com/robotics-sim:latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: AWS_REGION
              value: "us-west-2"
            - name: KINESIS_STREAM_NAME
              value: "robotics-sim-stream"
            - name: SIMULATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "250m"     # Increased slightly
              memory: "384Mi"
            limits:
              cpu: "500m"     # Increased slightly
              memory: "768Mi"
          command: ["/bin/sh", "-c"]
          args:
            - |
              python -u amazon-robotics-fulfillment-sim.py
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import os; exit(0 if os.path.exists('/tmp/sim_ready') else 1)"
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "touch /tmp/sim_ready"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -f /tmp/sim_ready"]