apiVersion: batch/v1
kind: Job
metadata:
  name: robotics-sim-job
  namespace: robotics-sim
spec:
  completions: 3
  parallelism: 3  # Reduced to match node count
  backoffLimit: 4  # Added retry limit
  template:
    metadata:
      labels:
        app: robotics-sim
    spec:
      restartPolicy: Never
      serviceAccountName: robotics-sim-sa
      containers:
        - name: robotics-sim
          image: 805791260265.dkr.ecr.us-west-2.amazonaws.com/robotics-sim:latest
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: KINESIS_STREAM_NAME
              value: "robotics-sim-stream"
            - name: SIMULATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "250m"     # Increased for t3.small (0.25 core)
              memory: "512Mi"  # Increased for better performance
            limits:
              cpu: "500m"     # 0.5 core limit
              memory: "1Gi"    # 1GB memory limit