apiVersion: v1
kind: ServiceAccount
metadata:
  name: robotics-sim-sa
  namespace: robotics-sim
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::805791260265:role/robotics-sim-kinesis-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: robotics-sim-role
  namespace: robotics-sim
rules:
- apiGroups: [""]
  resources: ["pods", "logs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robotics-sim-role-binding
  namespace: robotics-sim
subjects:
- kind: ServiceAccount
  name: robotics-sim-sa
  namespace: robotics-sim
roleRef:
  kind: Role
  name: robotics-sim-role
  apiGroup: rbac.authorization.k8s.io